[metadata]
name = "NODE"
size = 40
last_change = 1660015591

[members.0]
member_name = "a"
offset = 0
type = "int"
size = 4

[members.4]
member_name = "buff"
offset = 4
type = "char[10]"
size = 10

[members.10]
member_name = "b"
offset = 16
type = "int"
size = 4

[members.18]
member_name = "prev"
offset = 24
type = "struct NODE *"
size = 8

[members.20]
member_name = "next"
offset = 32
type = ""
size = 8
